### ISSUE TITLE
fix warning (puppet apply)

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/dotfiles#3]
```
Warning: The function 'hiera' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/5.3/reference/deprecated_language.html
   (file & line not available)
Warning: /home/sika/projects/dotfiles/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /home/sika/projects/dotfiles/hiera.yaml)
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/sudo/manifests/init.pp", 101]:["/etc/puppetlabs/code/environments/production/modules/sudo/manifests/conf.pp", 51]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/sudo/manifests/configs.pp", 13]:["/etc/puppetlabs/code/environments/production/modules/sudo/manifests/init.pp", 170]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: The function 'hiera_hash' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/5.3/reference/deprecated_language.html
   (file & line not available)
Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/etc/puppetlabs/code/environments/production/modules/sudo/manifests/conf.pp", 90]:
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: Unknown variable: '::git::package_manage'. at /etc/puppetlabs/code/environments/production/modules/git/manifests/config.pp:67:18
Warning: Unknown variable: '::git::package_manage'. at /etc/puppetlabs/code/environments/production/modules/git/manifests/config.pp:67:18
```

**Comment by ondrejsika** [comment]
Errors in my modules are fixed.
